export const ADD_USER = 'ADD_USER';
export const GET_STORAGE = 'GET_STORAGE';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const PLUS_COUNT = 'PLUS_COUNT';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN = 'LOG_IN';
export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_CHARACTER_REQUEST = 'GET_CHARACTER_REQUEST';
export const GET_CHARACTER_SUCCESS = 'GET_CHARACTER_SUCCESS';

